/**
 * @file tal_irq_handler.c
 *
 * @brief This file handles the interrupts generated by the transceiver.
 *
 * $Id: tal_irq_handler.c 37655 2015-07-17 08:00:49Z sschneid $
 *
 * @author    Atmel Corporation: http://www.atmel.com
 * @author    Support email: avr@atmel.com
 */
/*
 * Copyright (c) 2012, Atmel Corporation All rights reserved.
 *
 * Licensed under Atmel's Limited License Agreement --> EULA.txt
 */

/* === INCLUDES ============================================================ */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "pal.h"
#include "tal_config.h"
#include "tal_internal.h"

#include "ieee_const.h"

/* === TYPES =============================================================== */

/* === MACROS ============================================================== */

/* === EXTERNALS =========================================================== */

/* === GLOBALS ============================================================= */

/* === PROTOTYPES ========================================================== */

/* === IMPLEMENTATION ====================================================== */


/**
 * @brief Transceiver interrupt handler
 *
 * This function handles the transceiver interrupt. It reads all IRQs from the
 * transceivers and stores them to a variable. If a transceiver is currently
 * sleeping, then the IRQs are not handled.
 * The actual processing of the IRQs is triggered from tal_task().
 */
void trx_irq_handler_cb(void)
{

    /* Get all IRQS values */
    uint8_t irqs_array[4];

    pal_dev_read(RF215_TRX, RG_RF09_IRQS, irqs_array, 4);

    /* Handle BB IRQS */
    for (trx_id_t trx_id = (trx_id_t)0; trx_id < NUM_TRX; trx_id++)
    {
        if (tal_state[trx_id] == TAL_SLEEP)
        {
            continue;
        }

        bb_irq_t irqs = (bb_irq_t)irqs_array[trx_id + 2];

        if (irqs != BB_IRQ_NO_IRQ)
        {
            if (irqs & BB_IRQ_RXEM)
            {
                irqs &= (uint8_t)(~((uint32_t)BB_IRQ_RXEM)); // avoid Pa091
            }
            if (irqs & BB_IRQ_RXAM)
            {
                irqs &= (uint8_t)(~((uint32_t)BB_IRQ_RXAM)); // avoid Pa091
            }
            if (irqs & BB_IRQ_AGCR)
            {
               
#if ((defined RF215v1) || (defined RF215v2)) && (defined SUPPORT_LEGACY_OQPSK)
                /* Workaround for errata reference #4908 */
                /* Keep flag set to trigger workaround; see tal.c */
#else
                irqs &= (uint8_t)(~((uint32_t)BB_IRQ_AGCR)); // avoid Pa091
#endif
            }
            if (irqs & BB_IRQ_AGCH)
            {
				
#if ((defined RF215v1) || (defined RF215v2)) && (defined SUPPORT_LEGACY_OQPSK)
                /* Workaround for errata reference #4908 */
                /* Keep flag set to trigger workaround; see tal.c */
#else
                irqs &= (uint8_t)(~((uint32_t)BB_IRQ_AGCH)); // avoid Pa091
#endif
            }
            if (irqs & BB_IRQ_RXFS)
            {
                
#ifdef ENABLE_TSTAMP
                pal_get_current_time(&fs_tstamp[trx_id]);
#endif
#if ((defined RF215v1) || (defined RF215v2)) && (defined SUPPORT_LEGACY_OQPSK)
                /* Workaround for errata reference #4908 */
                /* Keep flag set to trigger workaround; see tal.c */
#else
                irqs &= (uint8_t)(~((uint32_t)BB_IRQ_RXFS)); // avoid Pa091
#endif
            }
            if (irqs & BB_IRQ_RXFE)
            {
                pal_get_current_time(&rxe_txe_tstamp[trx_id]);
#if (defined RF215v1) 
                /* Workaround for errata reference #4830 */
                /* Check if ACK transmission is actually requested by the received frame */
                uint16_t buf_reg_offset = BB_RX_FRM_BUF_OFFSET * trx_id;
                uint8_t fcf0 = pal_dev_reg_read(RF215_TRX, buf_reg_offset + RG_BBC0_FBRXS);
                if ((fcf0 & FCF_ACK_REQUEST) == 0x00)
                {
                    /* Ensure ACK is not transmitted */
                    
                    uint16_t offset = RF_BASE_ADDR_OFFSET * trx_id;
                    pal_dev_bit_write(RF215_TRX, offset + SR_BBC0_AMCS_AACK, 0);
                    pal_dev_bit_write(RF215_TRX, offset + SR_BBC0_AMCS_AACK, 1);
                }
#endif
            }
            if (irqs & BB_IRQ_TXFE)
            {
                /* used for IFS and for MEASURE_ON_AIR_DURATION */
                pal_get_current_time(&rxe_txe_tstamp[trx_id]);
            }

            /*
             * Store remaining flags to global TAL variable and
             * handle them within tal_task()
             */
            tal_bb_irqs[trx_id] |= irqs;
        }
    }

    /* Handle RF IRQS */
    for (trx_id_t trx_id = (trx_id_t)0; trx_id < NUM_TRX; trx_id++)
    {
        if (tal_state[trx_id] == TAL_SLEEP)
        {
            continue;
        }

        rf_irq_t irqs = (rf_irq_t)irqs_array[trx_id];

        if (irqs != RF_IRQ_NO_IRQ)
        {
            if (irqs & RF_IRQ_TRXRDY)
            {
                irqs &= (uint8_t)(~((uint32_t)RF_IRQ_TRXRDY)); // avoid Pa091
            }
            if (irqs & RF_IRQ_TRXERR)
            {
                irqs &= (uint8_t)(~((uint32_t)RF_IRQ_TRXERR)); // avoid Pa091
            }
            tal_rf_irqs[trx_id] |= irqs;
        }
    }
}/* trx_irq_handler_cb() */

/* EOF */
